version: '3.6'

services:
  engine:
    container_name: 'flask-starting-engine'
    build:
      context: services/engine
      dockerfile: Dockerfile-dev
    volumes:
      - './services/engine:/usr/src/app'
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=manage
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://flask_startinguser:flask_startingpassword@engine-db:5432/flask_starting
    depends_on:
      - engine-db
    restart: on-failure

  engine-db:
    container_name: 'flask-starting-engine-db'
    build:
      context: services/engine/db
      dockerfile: Dockerfile
    volumes:
      - engine-db_volume:/usr/local/pgsql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=flask_startinguser
      - POSTGRES_PASSWORD=flask_startingpassword

  nginx:
    container_name: 'flask-starting-nginx'
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-dev
    restart: on-failure
    ports:
      - 80:80
    depends_on:
      - engine

volumes:
  engine-db_volume:
